### ISSUE TITLE
maxLenght is not taken into account

### ISSUE THREAD

**Issue by lucj** [MosesEsan/react-native-basic-form#5]
To limit the number of char for a TYPES.Number field I use the maxLength properties but it is not taken into account in the form.

 ```
   const fields = [
      {
         name: 'value',
         label: 'Enter a numeric value',
         required: true,
         type:TYPES.Number,
         maxLength: 10
      }
    ];
```

**Comment by MosesEsan** [comment]
@lucj Hi, this is a basic component, the documentation details what is possible, feel free to add more capabilities and create  a pull request

**Comment by lucj** [comment]
Hi @MosesEsan I'm not that fluent in react-native yet but I'll try :)
